version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run: pip install --user -r requirements.txt -r requirements.dev.txt
      - python/save-cache
      - run: make test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  main:
    jobs:
      - build-and-test

